# No comments in messages.
no-comments

# No version.
no-emit-version

# No banner.
no-greeting

# Output ASCII instead of binary.
armor

# Use long keyid format.
keyid-format 0xlong

# Disable caching for symmetrical ops.
no-symkey-cache

# Enforce memory locking.
require-secmem
