#!/bin/bash

# Source OS release variables.

if [ -f /etc/os-release ]
then
  source /etc/os-release
  OS=$ID
fi

# Deal with special cases.

case $(/bin/cat /proc/version 2>/dev/null) in
  *Chromium\ OS*)            OS="chromeos";;
  *microsoft-standard-WSL2*) OS="wsl";;
esac

# Locate the base directory of the repository.

THIS_SCRIPT=$(readlink -f $0)
BASE_DIR=$(dirname $THIS_SCRIPT)
ETC_DIR="${BASE_DIR}/etc"
SCRIPT_DIR="${BASE_DIR}/etc/setup"
LOCAL_DIR="${HOME}/.local"
LOCAL_BIN="${LOCAL_DIR}/bin"

# Pretty colours.

GOTO_COLUMN="\\033[74G"
RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
BLUE='\033[00;36m'
CLEAR='\033[00m'

# Function that runs setup scripts.

setup () {
  local script="${1}"
  local dir="${1/\/*}"
  local name="${1/*\/}"
  shift
  if [ -f "${SCRIPT_DIR}/${script}.sh" ]
  then
    if [ "${dir}" == "${name}" ]
    then
      echo -e "${BLUE}${script}:${CLEAR}"
    else
      echo -e "${BLUE}${name} for ${dir}:${CLEAR}"
    fi
    source "${SCRIPT_DIR}/${script}.sh" "$@"
  fi
}

# Sent a notice to stderr.

notice () { echo -en " - ${1^} " 1>&2; }

# Non-fatal feedback is sent to stderr.

pass () { echo -e "${GOTO_COLUMN}${GREEN}Done${CLEAR}" 1>&2; }
fail () { echo -e "${GOTO_COLUMN}${YELLOW}Failed${CLEAR}" 1>&2; return 1; }
yes () { echo -e "${GOTO_COLUMN}${GREEN}Yes${CLEAR}" 1>&2; }
no () { echo -e "${GOTO_COLUMN}${YELLOW}No${CLEAR}" 1>&2; return 1; }

# Fatal feedback that ends the script immediately.

fatal () {
  echo -e "${GOTO_COLUMN}${RED}Failed${CLEAR}" 1>&2;
  [ $# -eq 0 ] && exit 1
  echo -e "${RED}Error:${CLEAR} $@" 1>&2
  exit 1
}

usage () {
  [ ! -z ${1:+z} ] && echo -e "${YELLOW}Usage:${CLEAR} setup ${SCRIPT}" "$@" 1>&2
  exit 1
}

# Work out whether to run commands using sudo.

SUDO=sudo
if [ $(id -u) -eq 0 ]
then
  SUDO=""
  setup_needs_sudo () {
    notice "checking whether user is root"
    yes
  }
else
  setup_needs_sudo () {
    notice "checking whether user has sudo access"
    if [ ! -z ${SUDO} ]
    then
      if sudo -n /bin/true 2>/dev/null
      then
        yes
      else
        no
        sudo -v
        notice "confirming that user has sudo access"
        sudo -n /bin/true 2>/dev/null && yes || fatal "no sudo access"
      fi
    fi
  }
fi

# Check that symlink is set up.

[ -d $LOCAL_BIN ] || mkdir -p $LOCAL_BIN &>/dev/null
ln -fs $BASE_DIR/setup $LOCAL_BIN/setup &>/dev/null

# Get the name of the setup script from the command line.

SCRIPT=""
if [ ! -z ${1:+z} ]
then
  SCRIPT="${1}"
  shift
fi

# Work out the path to the setup script.

SCRIPT_FILE="${SCRIPT_DIR}/${SCRIPT}.sh"
if [ ! -f $SCRIPT_FILE ]
then

  # Print a usage message listing all available setup scripts.

  AVAILABLE_SCRIPTS="<"
  for FILE in "${SCRIPT_DIR}/"*
  do
    NAME=$(basename -s .sh $FILE)
    AVAILABLE_SCRIPTS+="${NAME}|"
  done
  echo -e "${YELLOW}Usage:${CLEAR} setup ${AVAILABLE_SCRIPTS/%|/>}" 1>&2
fi

# Run the setup script.

setup "${SCRIPT}"
