#!/bin/bash

# Source OS release variables.

if [ -f /etc/os-release ]
then
  source /etc/os-release
  OS=$ID
fi

# Deal with special cases.

case $(/bin/cat /proc/version 2>/dev/null) in
  *Chromium\ OS*)            OS="chromeos";;
  *microsoft-standard-WSL2*) OS="wsl";;
esac

# Locate the base directory of the repository.

THIS_SCRIPT=$(readlink -f $0)
BASE_DIR=$(dirname $THIS_SCRIPT)
ETC_DIR="${BASE_DIR}/etc"
SCRIPT_DIR="${BASE_DIR}/etc/setup"
LOCAL_DIR="${HOME}/.local"
LOCAL_BIN="${LOCAL_DIR}/bin"

# Windows directories in WSL.

SYSTEM_DIR="/mnt/c/Windows/System32"
USER_PROFILE_DIR="/mnt/c/Users/${USER}"
APPDATA_LOCAL_DIR="${USER_PROFILE_DIR}/AppData/Local"

# Pretty feedback.

GOTO_COLUMN="\\033[74G"
RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
CLEAR='\033[00m'

notice () { echo -en "${1^} " 1>&2; }
pass () { echo -e "${GOTO_COLUMN}${GREEN}Done${CLEAR}" 1>&2; }
fail () { echo -e "${GOTO_COLUMN}${YELLOW}Failed${CLEAR}" 1>&2; return 1; }
yes () { echo -e "${GOTO_COLUMN}${GREEN}Yes${CLEAR}" 1>&2; }
no () { echo -e "${GOTO_COLUMN}${YELLOW}No${CLEAR}" 1>&2; return 1; }

fatal () {
  echo -e "${GOTO_COLUMN}${RED}Failed${CLEAR}" 1>&2;
  [ $# -eq 0 ] && exit 1
  echo -e "${RED}Error:${CLEAR} $@" 1>&2
  exit 1
}

usage () {
  [ ! -z ${1:+z} ] && echo -e "${YELLOW}Usage:${CLEAR} setup ${SCRIPT}" "$@" 1>&2
  exit 1
}

# Work out whether to run commands using sudo.

SUDO=sudo
if [ $(id -u) -eq 0 ]
then
  SUDO=""
  setup_needs_sudo () {
    notice "checking that user is root"
    pass
  }
else
  setup_needs_sudo () {
    notice "checking that user has sudo access"
    if [ ! -z ${SUDO} ]
    then
      if sudo -n /bin/true 2>/dev/null
      then
        pass
      else
        fail
        sudo -v
        notice "checking sudo access again"
        sudo -n /bin/true 2>/dev/null && pass || fatal "no sudo access"
      fi
    fi
  }
fi

# Check that symlink is set up.

if [ ! -d $LOCAL_BIN ]
then
  mkdir -p $LOCAL_BIN
fi

if [ -L $LOCAL_BIN/setup ]
then
  rm -f $LOCAL_BIN/setup
fi
ln -s $BASE_DIR/setup $LOCAL_BIN/setup

# Get the name of the setup script from the command line.

SCRIPT=""
if [ ! -z ${1:+z} ]
then
  SCRIPT="${1}"
  shift
fi

# Work out the path to the setup script.

SCRIPT_FILE="${SCRIPT_DIR}/${SCRIPT}.sh"
if [ ! -f $SCRIPT_FILE ]
then

  # Print a usage message listing all available setup scripts.

  AVAILABLE_SCRIPTS="("
  for FILE in "${SCRIPT_DIR}/"*
  do
    NAME=$(basename -s .sh $FILE)
    AVAILABLE_SCRIPTS+="${NAME}|"
  done
  usage "${AVAILABLE_SCRIPTS/%|/)}"
fi

# Function to call setup scripts from other setup scripts.

setup () {
  local script="${1}"
  shift
  if [ -f "${SCRIPT_DIR}/${script}.sh" ]
  then
    source "${SCRIPT_DIR}/${script}.sh" "$@"
  fi
}

# Run the setup script.

setup "${SCRIPT}" "$@"
