# Use tty-based pinentry
pinentry-program /usr/bin/pinentry-tty

# Set the default cache timeout for passphrases (in seconds)
default-cache-ttl 600

# Set the maximum cache timeout for passphrases (in seconds)
max-cache-ttl 7200

# Enable use of the gpg-agent for SSH
enable-ssh-support
