# Set the tty and use tty-based pinentry
ttyname $GPG_TTY
pinentry-program /usr/bin/pinentry-tty

# Set the default cache timeouts for passphrases (1 hour / 4 hours)
default-cache-ttl 3600
max-cache-ttl 14400

# Enable use of the gpg-agent for SSH
enable-ssh-support
