# Use tty-based pinentry
pinentry-program /usr/bin/pinentry-tty

# Set the default cache timeout for passphrases (3600 seconds = 1 hour)
default-cache-ttl 3600

# Set the maximum cache timeout for passphrases (28800 seconds = 8 hours)
max-cache-ttl 28800

# Enable use of the gpg-agent for SSH
enable-ssh-support
