# Do not cache symmetric key passphrases and require secure memory.

no-symkey-cache
require-secmem

# Tidy up output.

no-comments
no-emit-version
no-greeting
keyid-format 0xlong

# Export in ascii format by default.

armor
